services:
    database:
        image: postgres:latest
        container_name: nexo_erp_database_container
        networks:
            - development_network
        environment:
            POSTGRES_USER: adminuser
            POSTGRES_PASSWORD: AdminPassword
            POSTGRES_DB: nexo_erp
        ports:
            - "5432:5432"
    redis:
        image: redis:latest
        container_name: nexo_erp_redis_container
        networks:
            - development_network
        ports:
            - "6379:6379"

networks:
    development_network:
        driver: bridge