ALTER TABLE stocks ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE products ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE stock_items ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT false;
