apiVersion: apps/v1
kind: Deployment
metadata:
    name: backend-deployment
spec:
    replicas: 2
    selector:
        matchLabels:
            app: backend
    template:
        metadata:
            labels:
                app: backend
        spec:
            containers:
                - name: backend
                  image: kicklob/nexo-erp-backend:latest
                  imagePullPolicy: Always
                  ports:
                    - containerPort: 8080
                  env:
                    - name: ENVIRONMENT
                      value: "development"
                    - name: SERVER_PORT
                      value: "8080"
                    - name: DB_HOST
                      valueFrom:
                          configMapKeyRef:
                                name: database-cm
                                key: POSTGRES_HOST
                    - name: DB_PORT
                      valueFrom:
                          configMapKeyRef:
                                name: database-cm
                                key: POSTGRES_PORT
                    - name: DB_USER
                      valueFrom:
                          configMapKeyRef:
                                name: database-cm
                                key: POSTGRES_USER
                    - name: DB_PASSWORD
                      valueFrom:
                          configMapKeyRef:
                                name: database-cm
                                key: POSTGRES_PASSWORD
                    - name: DB_NAME
                      valueFrom:
                          configMapKeyRef:
                                name: database-cm
                                key: POSTGRES_DB
                    - name: REDIS_HOST
                      value: "redis-svc"
                    - name: REDIS_PORT
                      value: "6379"
                    - name: JWT_SECRET
                      value: "123456"
                    - name: FRONTEND_HOST
                      value: "http://frontend:8081"
                    - name: PORTAL_HOST
                      value: "http://portal:8082"
