apiVersion: apps/v1
kind: Deployment
metadata:
    name: database-deploy
spec:
    replicas: 1
    selector:
        matchLabels:
            app: database
    template:
        metadata:
            labels:
                app: database
        spec:
            containers:
                - name: database
                  image: postgres:latest
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 5432
                  envFrom:
                      - configMapRef:
                            name: database-cm
