apiVersion: v1
kind: Service
metadata:
    name: frontend-svc
spec:
    type: LoadBalancer
    selector:
        app: frontend
    ports:
        - port: 3000
          targetPort: 80
          nodePort: 30002
