apiVersion: v1
kind: Service
metadata:
    name: portal-svc
spec:
    type: LoadBalancer
    selector:
        app: portal
    ports:
        - port: 3001
          targetPort: 80
          nodePort: 30003
