CREATE EXTENSION citext;

CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    username CITEXT UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    roles JSONB NOT NULL
);