spring:
  servlet:
    multipart:
      max-file-size: '5MB'
      max-request-size: '5MB'
      enabled: true
  application:
    name: 'NexoERP'
  datasource:
    url: 'jdbc:postgresql://localhost:5432/nexo_erp'
    username: 'adminuser'
    password: 'AdminPassword'
  data:
    redis:
      host: 'localhost'
      port: 6379
frontend:
  host: 'http://localhost:8081'